### ISSUE TITLE
Make a new release for csctl

### ISSUE THREAD

**Issue by michal-gubricky** [SovereignCloudStack/csctl#133]
IMHO, it would be great and useful to create a new release for `csctl`, as new and important features such as the ability to call the csctl plugin have been introduced and are not included in the `v0.0.2` release. I can create a new one. I just wanted to know your opinion on this @janiskemper. If it's ok or you want to implement more features before the next release.

/kind proposal

**Comment by janiskemper** [comment]
thanks! good idea. @kranurag7 can take care of this. @michal-gubricky do you use the current main? Do you have any doubts?

**Comment by kranurag7** [comment]
> I can create a new one.

@michal-gubricky given you wanted to create one, I think you can proceed here. Ping me if something goes wrong.

**Comment by michal-gubricky** [comment]
> thanks! good idea. @kranurag7 can take care of this. @michal-gubricky do you use the current main? Do you have any doubts?

Yes, I use the current main branch and it is also used in e2e pipeline and works well so far.
