### ISSUE TITLE
:bug: create command always checks GitHub for last release, even when OCI is wanted

### ISSUE THREAD

**Issue by jschoone** [SovereignCloudStack/csctl#159]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
```
git clone https://github.com/SovereignCloudStack/cluster-stacks
git clone https://github.com/SovereignCloudStack/csctl
cd csctl
make build
./csctl create ../cluster-stacks/providers/openstack/scs
```
Got error `Error: failed to create create options: failed to create new github client: failed to create git config: environment variable GIT_PROVIDER is not set` which is correct in general, but I only want to use an OCI registry

**What did you expect to happen:**
When no GIT_* env vars are set, the `csctl` tool could check if there are OCI_* env vars available instead to check for the latest stable version there.
Alternatively or additionally and maybe even more stable could be a flag to set the target, since both GIT_* and OCI_* could be set. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- csctl version: (use `csctl version`)
- OS (e.g. from `/etc/os-release`):

**Comment by jschoone** [comment]
In analysis with @DEiselt and @paulphys we found out it is more or less only necessary to change the `github` in https://github.com/SovereignCloudStack/csctl/blob/67ba98a679f2ee7b4b29d664f4484702ad511956/pkg/cmd/publish.go#L121 to `oci`. But then obviously `github` stops working.
Generally we discussed those changes/additions needs to be implemented:

- [ ] add a flag to set the assetsclient, with options `oci` and `github` (`github` as default)
- [ ] lookup specific env vars (`OCI_` or `GIT_`) only when appropriate assetsclient is set
- [ ] deduplicate code in publish.go and create.go

**Comment by DEiselt** [comment]
Note: publish is not implemented for github clients. This needs to be checked and handled accordingly.
